include = "./repositories"

[database]
address = "127.0.0.1"
port = 3306
username = "root"
password = ""
dbname = "cherry_picker"

[slack]
heartbeat = "admin@pingcap.com"
token = ""
mute = false
hello = false

[github]
token = ""
bot = "cherry-picker"

[member]
orgs = ["pingcap"]
users = ["sre-bot"]

[email]
sender_addr = "xxx@pingcap.com"
default_receiver_addr = ["xxx@pingcap.com"]
special_password = "123456789"

[check]
white_list = ["pingcap/tidb","you06/tiedb"]
